# Machine operation
The machine operation withan supervisor can be explained as the folowing.

In [2]:
import numpy as np

In [4]:
Supervised = np.matrix([[0, 0.98, 0.02],[0, 0.95, 0.05],[0, 0.40, 0.60]])
Supervised

matrix([[ 0.  ,  0.98,  0.02],
        [ 0.  ,  0.95,  0.05],
        [ 0.  ,  0.4 ,  0.6 ]])

In [6]:
UnSupervised = np.matrix([[0.9, 0.1],[0.4, 0.6]])
UnSupervised 

matrix([[ 0.9,  0.1],
        [ 0.4,  0.6]])

Starting position in this example can be modeld by a row matrix like
[Alert, Tierd, Repair]
Thus as we start at Alert we get:

In [8]:
StartS = np.matrix([1,0,0])
StartS

matrix([[1, 0, 0]])

The matrix for the un supervised machine [Running, Repair]

In [10]:
StartU = np.matrix([1, 0])
StartU

matrix([[1, 0]])

Then because for example a 8 hour shift can be calculated by

In [44]:
ShitSupervised = StartS * Supervised**8
ShiftUnSupervised = StartU * UnSupervised**8
temp1 = ShitSupervised.tolist()
temp2 = ShiftUnSupervised.tolist()
print("ShiftSupervised=" + str(ShitSupervised) + " ShiftUnSupervised=" + str(ShiftUnSupervised))
print("i.e")
print("When supervised the risk of that the machine is under repari is " + str(round(temp1[0][2] * 100, 2)) + "%")
print("While un superviced the risk of that the machine is under repari is "+ str(round(temp2[0][1] * 100,2)) + "%")

ShiftSupervised=[[ 0.        0.890276  0.109724]] ShiftUnSupervised=[[ 0.80078125  0.19921875]]
i.e
When supervised the risk of that the machine is under repari is 10.97%
While un superviced the risk of that the machine is under repari is 19.92%
